services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./api/src
          target: /app/src
        - action: sync+restart
          path: ./api/deno.json
          target: /app/deno.json
    depends_on:
      - postgres
      - redis
    command: "deno task watch"

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./worker/src
          target: /app/src
        - action: sync+restart
          path: ./worker/deno.json
          target: /app/deno.json
    depends_on:
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src
        - action: sync+restart
          path: ./client/package.json
          target: /app/package.json

  nginx:
    restart: on-failure
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - client

volumes:
  postgres-data:
  redis-data: