services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5100:5100"
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/src
        - action: sync+restart
          path: ./server/deno.json
          target: /app/deno.json
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5200:5200"
    develop:
      watch:
        - action: sync
          path: ./worker/src
          target: /app/src
        - action: sync+restart
          path: ./worker/deno.json
          target: /app/deno.json
    depends_on:
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src
        - action: sync+restart
          path: ./client/package.json
          target: /app/package.json

volumes:
  postgres-data:
  redis-data: